### ISSUE TITLE
Updated list - CTL3.0 and Robinworldwide

### ISSUE THREAD

**Issue by slammajamma28** [DouglasKGlover/PSTCTL_V2#1]
[Updated_list.txt](https://github.com/DouglasKGlover/PSTCTL_V2/files/1869843/Updated_list.txt)
I attached the updated list, including the remainder of the known CTL3.0 and Robinworldwide's list.

**Comment by DouglasKGlover** [comment]
I have updated the lists.js with the provided code. Tested and looks to work just fine, so pushed to production. Cheers!
